@startuml

skinparam sequenceReferenceBackgroundColor lightblue
participant "handler:Handler" as Handler
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation
participant "newAppointment:Appointment" as Appointment
participant "healthList:HealthList" as HealthList
participant "output:Output" as Output

Handler -> Parser: parseAppointmentInput()
activate Handler #salmon
activate Parser #salmon

Parser -> Parser: splitAppointmentDetails()
activate Parser #FFBBBB
Parser --> Parser: appointmentDetails[]
deactivate Parser #FFBBBB

Parser -> Validation: validateAppointmentDetails()
activate Validation #FFBBBB
Validation --> Parser:
deactivate Validation

Parser -> Appointment **: new
activate Appointment #FFBBBB

Appointment -> HealthList **: new
activate HealthList #FFBBBB
Appointment -> HealthList: addAppointment(date,time,description)
HealthList --> Appointment:
deactivate HealthList #FFBBBB
destroy HealthList
Appointment --> Parser:
deactivate Appointment #FFBBBB



Parser -> Output: printAddAppointment()
activate Output #FFBBBB
Output --> Parser:
destroy Appointment
deactivate Output #FFBBBB

@enduml