@startuml

skinparam sequenceReferenceBackgroundColor lightblue
participant "handler:Handler" as Handler
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation
participant "newBmi:Bmi" as NBmi
participant "healthList:HealthList" as HealthList
participant "Bmi" as Bmi << Class>>
participant "output:Output" as Output

Handler -> Parser: parseBmiInput()
activate Handler #salmon
activate Parser #salmon

Parser -> Parser: splitBmiInput()
activate Parser #FFBBBB
Parser --> Parser: bmiDetails[]
deactivate Parser #FFBBBB

Parser -> Validation: validateBmiInput()
activate Validation #FFBBBB
Validation --> Parser:
deactivate Validation

Parser -> NBmi **: new
activate NBmi #FFBBBB
NBmi -> NBmi: calculateBmiValue
activate NBmi #DarkSalmon
NBmi --> NBmi: bmiValue
deactivate NBmi #DarkSalmon


NBmi -> Bmi: getBmiCategory(bmiValue)
activate Bmi #FFBBBB
Bmi --> NBmi: bmiCategory
deactivate Bmi #FFBBBB

NBmi -> HealthList **: new
activate HealthList #FFBBBB
NBmi -> HealthList: addBmi()
HealthList --> NBmi:
deactivate HealthList #FFBBBB
destroy HealthList


NBmi --> Parser:
deactivate NBmi #FFBBBB

Parser -> Output: printAddBmi()
activate Output #FFBBBB
Output --> Parser:
destroy NBmi
deactivate Output #FFBBBB

@enduml