@startuml
skinparam sequenceReferenceBackgroundColor lightblue

participant "handler:Handler" as Handler
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation


activate Handler #FFBBBB
Handler -> Handler: handleDelete() 
activate Handler #salmon
Handler -> Parser:  parseDeleteInput()


activate Parser #FFBBBB

Parser -> Parser: splitDeleteInput()
activate Parser #salmon
Parser --> Parser: deleteDetails
deactivate Parser #salmon

Parser -> Validation: validateDeleteInput()
alt if valid filter
    activate Validation #FFBBBB
    Validation --> Parser: validDeleteDetails
    
else not valid filter
    Validation --> Parser: null
    deactivate Validation
end

Parser --> Handler: validDeleteDetails
deactivate Parser #FFBBBB
deactivate Handler #salmon

Handler -> Handler: deleteItem(validDeleteDetails)
activate Handler #salmon
Handler --> Handler:
deactivate Handler

deactivate Handler
@enduml