@startuml
skinparam sequenceReferenceBackgroundColor lightblue

participant "handler:Handler" as Handler
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation
participant "newGym:Gym" as Gym
participant "workout:Workout" as Workout
participant "workoutList:WorkoutList" as WorkoutList

Handler -> Parser: parseGymInput()
activate Handler #salmon
activate Parser #salmon

Parser -> Parser: splitGymInput()
activate Parser #FFBBBB
Parser --> Parser: gymDetails[]
deactivate Parser #FFBBBB

Parser -> Validation: validateGymInput()
activate Validation #FFBBBB
Validation --> Parser: 
deactivate Validation

Parser -> Gym **: new


    activate Gym #FFBBBB   
    Gym -> Workout **: new()
    activate Workout #FFBBBB
    Workout --> Gym: 
    deactivate Workout #FFBBBB

    Gym -> Workout: addIntoWorkoutList()
    activate Workout #FFBBBB
    Workout -> WorkoutList **: new
    activate WorkoutList #FFBBBB
    WorkoutList --> Workout:
    deactivate WorkoutList #FFBBBB

    Workout -> WorkoutList: addGym()
    activate WorkoutList #FFBBBB
    WorkoutList --> Workout:
    deactivate WorkoutList #FFBBBB
    destroy WorkoutList
    
    Workout --> Gym :
    deactivate Workout #FFBBBB
    destroy Workout

Gym --> Parser:
deactivate Gym #FFBBBB

Parser -> Parser: parseGymStationInput()
activate Parser #FFBBBB
ref over Parser: parseGymStationInput
Parser --> Parser:
deactivate Parser #FFBBBB
Parser --> Handler 

deactivate Parser #salmon
deactivate Handler #salmon
@enduml