@startuml
mainframe **sd** validateGymInput
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation

activate Parser  #DarkSalmon
Parser -> Validation : validateGymInput()
activate Validation #FFBBBB

Validation -> Validation : isEmptyParameterPresent()
activate Validation  #DarkSalmon
Validation --> Validation :
deactivate Validation  #DarkSalmon

alt number of stations is not positive integer
    Validation --> Parser: InvalidInput exception
end

Validation -> Validation: validateDateNotEmpty()
activate Validation  #DarkSalmon
Validation --> Validation : isDatePresent
deactivate Validation #DarkSalmon

alt date is present
    
    Validation -> Validation : validateDateInput()
    activate Validation  #Red
    Validation --> Validation :
    deactivate Validation  #Red
    Validation -> Validation : validateDateNotAfterToday()
    activate Validation  #Red
    Validation --> Validation :
    deactivate Validation  #Red
    Validation --> Parser:

else date is not present
    Validation --> Parser:
    deactivate Validation
end
@enduml