@startuml
skinparam sequenceReferenceBackgroundColor lightblue

participant "handler:Handler" as Handler
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation
participant "newGym:Gym" as Gym
participant "workout:Workout" as Workout
participant "workoutList:WorkoutList" as WorkoutList
participant "parser:Parser" as newParser

Handler -> Parser: parseGymInput()
activate Handler #salmon
activate Parser #salmon

Parser -> Parser: splitGymInput()
activate Parser #FFBBBB
Parser --> Parser: gymDetails[]
deactivate Parser #FFBBBB

Parser -> Validation: validateGymInput()
activate Validation #FFBBBB
Validation --> Parser: 
deactivate Validation

Parser -> Gym **: new



alt date is present
    activate Gym #FFBBBB   
    Gym -> Workout **: <<super>> Super(date)
    activate Workout #FFBBBB
    Workout -> newParser **: parseDate(date)
    activate newParser #FFBBBB
    newParser --> Workout:
    deactivate newParser #FFBBBB
    destroy newParser

    Workout -> Workout: addIntoWorkoutList()
    activate Workout #salmon
    Workout -> WorkoutList **: addGym()
    activate WorkoutList #FFBBBB
    WorkoutList --> Workout:
    deactivate WorkoutList #FFBBBB
    destroy WorkoutList

    Workout --> Workout :
    deactivate Workout #Salmon

    Workout --> Gym:
    deactivate Workout #FFBBBB
 
else date is not present
    Gym -> Workout **: <<super>> Super()
    activate Workout #FFBBBB
    Workout -> newParser **: parseDate(date)
    activate newParser #FFBBBB
    newParser --> Workout:
    deactivate newParser #FFBBBB
    destroy newParser

    Workout -> Workout: addIntoWorkoutList()
    activate Workout #salmon
    Workout -> WorkoutList **: addGym()
    activate WorkoutList #FFBBBB
    WorkoutList --> Workout:
    deactivate WorkoutList #FFBBBB
    destroy WorkoutList

    Workout --> Workout :
    deactivate Workout #Salmon

    Workout --> Gym:
    deactivate Workout #FFBBBB
end
Gym --> Parser:
deactivate Gym #FFBBBB

Parser -> Parser: parseGymStationInput()
activate Parser #FFBBBB
ref over Parser: parseGymStationInput
Parser --> Parser:
deactivate Parser #FFBBBB

@enduml