@startuml
mainframe sd parseGymStationInput
actor User
participant "parser:Parser" as Parser
participant "newGym:Gym" as Gym
participant "output:Output" as Output
participant "gymStation:GymStation" as GymStation

activate Parser  #FFBBBB

Parser -> Parser : parseGymStationInput()
    activate Parser #DarkSalmon
        loop until all gym stations recorded

            User -> Parser: user input
            Parser -> Parser: splitGymStationInput()
            activate Parser #FFBBBB
            Parser --> Parser:

            deactivate Parser #DarkSalmon

            Parser -> Gym: addStation() 
            note right : Using the same gym object that has \n been created in Parser.

            activate Gym #FFBBBB

            Gym -> Gym : appendIntoStations()
            activate Gym #DarkSalmon
                Gym -> GymStation **: new
                activate GymStation #FFBBBB

                GymStation -> GymStation: checkInput
                note right: Consist of multiple \n validation checks
                activate GymStation #Salmon
                GymStation --> GymStation:
                deactivate GymStation #Salmon

                GymStation -> GymStation : processSets()
                activate GymStation #DarkSalmon

                    loop until all sets are recorded
                        GymStation -> GymSet **: new 
                        activate GymSet #FFBBBB
                        GymSet --> GymStation:
                        deactivate GymSet #FFBBBB
                        destroy GymSet

                    end


                GymStation --> GymStation
                deactivate GymStation #DarkSalmon


                GymStation --> Gym: 
                deactivate GymStation #FFBBBB
                destroy GymStation

            Gym --> Gym : 
            deactivate Gym #DarkSalmon
            Gym --> Parser:
            deactivate Gym #FFBBBB
        end
    Parser -> Output: printAddGym()
    activate Output #FFBBBB
    Output --> Parser:
    destroy Gym
    deactivate Output
    Parser --> Parser :
    deactivate Parser #DarkSalmon
@enduml