participant "handler:Handler" as Handler
participant "logFile:LogFile" as LogFile
participant "parser:Parser" as Parser
participant "dataFile:DataFile" as DataFile
participant "output:Output" as Output
participant "validation:Validation" as Validation
participant "in:Scanner" as Scanner

activate Handler #Salmon
Handler -> LogFile **: new
activate LogFile #FFBBBB
LogFile --> Handler: logFile
deactivate LogFile

Handler -> Parser **: new
activate Parser #FFBBBB 
Parser --> Handler
deactivate Parser
Handler -> DataFile **: new
activate DataFile #FFBBBB 
DataFile --> Handler
deactivate DataFile
Handler -> Output **: new
activate Output #FFBBBB 
Output --> Handler
deactivate Output
Handler -> Validation **: new
activate Validation #FFBBBB 
Validation --> Handler
deactivate Validation

Handler -> Scanner **: new
activate Scanner #FFBBBB
Scanner --> Handler
deactivate Scanner