@startuml
actor User
skinparam sequenceReferenceBackgroundColor lightblue
participant PulsePilot as PulsePilot <<Class>>

User -> PulsePilot: start bot
activate PulsePilot #Salmon
PulsePilot -> "handler:Handler" **: new
activate "handler:Handler" #FFBBBB
"handler:Handler" -> "handler:Handler": initialiseBot()
activate "handler:Handler" #DarkSalmon
ref over "handler:Handler": initialiseBot
"handler:Handler" --> "handler:Handler": bot started
deactivate "handler:Handler" #DarkSalmon
"handler:Handler" --> PulsePilot 
PulsePilot --> User: bot ready

loop infinitely
    User -> PulsePilot: user input
    PulsePilot -> "handler:Handler": user input
    "handler:Handler" -> "handler:Handler": processInput()
    ref over "handler:Handler": processInput
    activate "handler:Handler" #DarkSalmon
    alt input has no error
        "handler:Handler" --> "handler:Handler": processed command
        "handler:Handler" --> PulsePilot:
        PulsePilot --> User: success message
        
    else input has error
        "handler:Handler" --> "handler:Handler": error message
        "handler:Handler" --> PulsePilot:
        PulsePilot --> User: error message
        
    else exit command used
        "handler:Handler" --> "handler:Handler":  
        "handler:Handler" --> PulsePilot:
        break loop
        
        deactivate "handler:Handler" #DarkSalmon
        
        end
    end
end
    PulsePilot -> "handler:Handler": terminateBot()
    ref over "handler:Handler": terminateBot
    "handler:Handler" --> PulsePilot:
    destroy "handler:Handler"
    PulsePilot --> User: exit message
    deactivate PulsePilot
    destroy PulsePilot
@enduml