@startuml
mainframe sd printHistory
    Handler -> Output: printHistory(filter)
    activate Handler #FFBBBB
    activate Output #FFBBBB
        alt filter == WORKOUT
            Output -> Output: printWorkoutHistory()
            activate Output #Salmon
            Output --> Output
            deactivate Output #Salmon
        else filter == RUN
            Output -> Output: printRunHistory()
            activate Output #Salmon
            Output --> Output
            deactivate Output #Salmon
        else filter == GYM
            Output -> Output: printGymHistory()
            activate Output #Salmon
            Output --> Output
            deactivate Output #Salmon
        else filter == BMI
            Output -> Output: printBmiHistory()
            activate Output #Salmon
            Output --> Output
            deactivate Output #Salmon
        else filter == PERIOD
            Output -> Output: printPeriodHistory()
            activate Output #Salmon
            Output --> Output
            deactivate Output #Salmon
        else filter == APPOINTMENT
            Output -> Output: printAppointmentHistory()
            activate Output #Salmon
            Output --> Output
            deactivate Output #Salmon
        end
    Output --> Handler #FFBBBB 
    deactivate Output
    deactivate Handler #FFBBBB
@enduml