@startuml
skinparam sequenceReferenceBackgroundColor lightblue

mainframe **sd** processInput

participant "handler:Handler" as Handler
participant "logFile:LogFile" as LogFile
participant "output:Output" as Output

activate Handler #salmon
Handler -> LogFile: writeLog()
activate LogFile #FFBBBB
LogFile --> Handler:
deactivate LogFile

alt WORKOUT Command
    Handler -> Handler: handleWorkout()
    activate Handler #FFBBBB
    ref over Handler: handleWorkout

else HEALTH Command
    Handler -> Handler: handleHealth()
    ref over Handler: handleHealth

else HISTORY Command
    Handler -> Handler: handleHistory()
    ref over Handler: handleHistory

else LATEST Command
    Handler -> Handler: handleLatest()
    ref over Handler: handleLatest

else DELETE Command
    Handler -> Handler: handleDelete()
    ref over Handler: handleDelete

else HELP Command
    Handler -> Output: printHelp()
    activate Output #FFBBBB
    Output --> Handler: 
    deactivate Output


else Invalid Command
    Handler -> Output: printException()
    activate Output #FFBBBB
    Output --> Handler:
    deactivate Output

else EXIT Command
    Handler -> LogFile: writeLog()
    activate LogFile #FFBBBB
    LogFile --> Handler:
    deactivate LogFile
    Handler --> Handler: return
    ref over Handler: terminateBot
    deactivate Handler
end

deactivate Handler
@enduml