@startuml
mainframe **sd** validateRunInput
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation

activate Parser  #DarkSalmon
Parser -> Validation : validateRunInput()
activate Validation #FFBBBB

Validation -> Validation : isEmptyParameterPresent()
activate Validation  #DarkSalmon
Validation --> Validation : isEmptyParameterPresent

alt isEmptyParameterPresent == true
  Validation --> Parser: InsufficientInput exception
end
deactivate Validation  #DarkSalmon

Validation -> Validation : validateRunTimeInput()
activate Validation  #DarkSalmon
Validation --> Validation :
deactivate Validation  #DarkSalmon

alt distance is invalid 2dp number
  Validation --> Parser: InvalidInput exception
end

alt distance > 5000km
    Validation --> Parser: InvalidInput exception
end
    
alt distance <= 0km
    Validation --> Parser: InvalidInput exception
end

Validation -> Validation: validateDateNotEmpty()
activate Validation  #DarkSalmon
Validation --> Validation : isDatePresent
deactivate Validation #DarkSalmon

alt date is present
    
    Validation -> Validation : validateDateInput()
    activate Validation  #Red
    Validation --> Validation :
    deactivate Validation  #Red
    Validation -> Validation : validateDateNotAfterToday()
    activate Validation  #Red
    Validation --> Validation :
    deactivate Validation  #Red
    Validation --> Parser:

else date is not present
    Validation --> Parser:
    deactivate Validation
end
@enduml