@startuml
skinparam sequenceReferenceBackgroundColor lightblue
participant "handler:Handler" as Handler
participant "parser:Parser" as Parser
participant "validation:Validation" as Validation
participant "newRun:Run" as Run
participant "workout:Workout" as Workout
participant "workoutLists:WorkoutLists" as WorkoutLists
participant "output:Output" as Output
Handler -> Parser: parseRunInput()
activate Handler #salmon
activate Parser #salmon
Parser -> Parser: splitRunInput()
activate Parser #FFBBBB
Parser --> Parser: runDetails[]
deactivate Parser #FFBBBB
Parser -> Validation: validateRunInput(runDetails)
activate Validation #FFBBBB
Validation --> Parser: 
deactivate Validation
Parser -> Run **: new
activate Run #salmon
Run -> Workout **: new
activate Workout #salmon
Workout --> Run
deactivate Workout #salmon
Run -> Workout: addIntoWorkoutList(Run)
activate Workout #salmon
Workout -> WorkoutLists **: new
activate WorkoutLists #salmon
WorkoutLists --> Workout: 
deactivate WorkoutLists #salmon
Workout -> WorkoutLists: addRun()
activate WorkoutLists #salmon
WorkoutLists --> Workout: 
destroy WorkoutLists
Workout --> Run:
destroy Workout
Run --> Parser:
deactivate Run #FFBBBB
Parser -> Output: printAddRun()
activate Output #salmon
Output --> Parser:
deactivate Output #salmon
destroy Run
@enduml