@startuml
skinparam sequenceReferenceBackgroundColor lightblue

participant "handler:Handler" as Handler

participant "parser:Parser" as Parser
participant "validation:Validation" as Validation
participant "newRun:Run" as Run
participant "workoutList:WorkoutList" as WorkoutList
participant "output:Output" as Output

Handler -> Parser: parseRunInput()
activate Handler #salmon
activate Parser #salmon

Parser -> Parser: splitRunInput()
activate Parser #FFBBBB
Parser --> Parser: runDetails[]
deactivate Parser #FFBBBB

Parser -> Validation: validateRunInput()
activate Validation #FFBBBB
ref over Validation: validateRunInput 
Validation --> Parser: 
deactivate Validation

Parser -> Run **: new
activate Run #FFBBBB   
Run -> WorkoutList **: new
activate WorkoutList #FFBBBB
WorkoutList --> Run:
deactivate WorkoutList #FFBBBB

alt date is present
    Run -> WorkoutList: addRun(date)
    activate WorkoutList #FFBBBB
    WorkoutList -> WorkoutList: addWorkout(date)
    activate WorkoutList #DarkSalmon
    WorkoutList --> WorkoutList:
    deactivate WorkoutList #DarkSalmon
    WorkoutList --> Run:
    deactivate WorkoutList #FFBBBB

 
else date is not present
    Run -> WorkoutList: addRun()
    activate WorkoutList #FFBBBB
    WorkoutList -> WorkoutList: addWorkout()
    activate WorkoutList #DarkSalmon
    WorkoutList --> WorkoutList:
    deactivate WorkoutList #DarkSalmon
    WorkoutList --> Run:
    deactivate WorkoutList #FFBBBB
end
Run --> Parser:
deactivate Run #FFBBBB
Parser -> Output: printAddRun()
activate Output #FFBBBB
Output --> Parser:
deactivate Output #FFBBBB
destroy Run
@enduml