@startuml

mainframe sd setCycleLength
participant "healthList:HealthList" as HealthList
participant "period:Period" as Period


activate HealthList #FFBBBB
HealthList -> HealthList: PERIODS.add(period)
activate HealthList #DarkSalmon
HealthList --> HealthList:
deactivate HealthList #DarkSalmon

HealthList -> HealthList: PERIODS.sort()
activate HealthList #DarkSalmon
HealthList --> HealthList:
deactivate HealthList #DarkSalmon

loop while (i > 0)

HealthList -> HealthList: PERIODS.get(i-1)
activate HealthList #DarkSalmon
HealthList --> HealthList:
deactivate HealthList #DarkSalmon
HealthList -> HealthList: PERIODS.get(i)
activate HealthList #DarkSalmon
HealthList --> HealthList:
deactivate HealthList #DarkSalmon

HealthList -> Period: setCycleLength()
activate Period #FFBBBB
Period --> HealthList:
deactivate Period #FFBBBB
deactivate HealthList #FFBBBB

end


@enduml