@startuml
mainframe **sd** splitAndValidateGymStationInput
participant "handler:Handler" as Handler
participant "validation:Validation" as Validation

activate Handler #Salmon
Handler -> Validation: splitAndValidateGymStationInput()
activate Validation #salmon


Validation -> Validation: validateExerciseName()
activate Validation #darksalmon

alt Name is invalid or too long
    Validation --> Handler: InvalidInput exception

else Name is empty
    Validation --> Handler: InsufficientInput exception

deactivate Validation #darksalmon

end

alt sets is not integer or less than 1
    Validation --> Handler: InvalidInput exception
end

alt reps is not integer or less than 1
    Validation --> Handler: InvalidInput exception
end

alt invalid weights array
    Validation --> Handler: InvalidInput exception
end

alt weights array length != number of sets
    Validation --> Handler: InvalidInput exception
end

Validation --> Handler: validatedGymStationInputs[]
deactivate Validation
@enduml