@startuml

participant "handler:Handler" as Handler
participant "dataFile:DataFile" as DataFile

activate Handler #FFBBBB
Handler -> DataFile: saveDataFile()
activate DataFile #FFBBBB

DataFile -> DataFile: writeName()
activate DataFile #salmon
DataFile --> DataFile: name written
deactivate DataFile #salmon

DataFile -> DataFile: writeHealthData()
activate DataFile #salmon
DataFile --> DataFile: health data written
deactivate DataFile #salmon

DataFile -> DataFile: writeWorkoutData()
activate DataFile #salmon
DataFile --> DataFile: workout data written
deactivate DataFile #salmon

DataFile -> DataFile: writeHashToFile()
activate DataFile #salmon
DataFile --> DataFile: file hash written
deactivate DataFile #salmon

DataFile --> Handler: both hash and data\nfile written
deactivate DataFile #salmon
deactivate DataFile #FFBBBB

@enduml