@startuml
skinparam sequenceReferenceBackgroundColor lightblue

mainframe **sd** terminateBot

participant "handler:Handler" as Handler
participant "logFile:LogFile" as LogFile
participant "dataFile:DataFile" as DataFile
participant "output:Output" as Output

activate Handler #salmon
Handler -> LogFile: writeLog()
activate LogFile #FFBBBB
LogFile --> Handler:
deactivate LogFile

alt no file write error
    Handler -> LogFile: writeLog()
    activate LogFile #FFBBBB
    LogFile --> Handler:
    deactivate LogFile

    Handler -> DataFile: saveDateFile()
    activate DataFile #FFBBBB
    DataFile --> Handler:
    deactivate DataFile

    Handler -> LogFile: writeLog()
    activate LogFile #FFBBBB
    LogFile --> Handler:
    deactivate LogFile

else file write error
    Handler -> Output: printException()
    activate Output #FFBBBB
    Output --> Handler:
    deactivate Output
end

Handler -> Output: printGoodbyeMessage()
activate Output #FFBBBB
Output --> Handler:
deactivate Output

Handler -> LogFile: writeLog()
activate LogFile #FFBBBB
LogFile --> Handler:
deactivate LogFile

destroy Output
destroy DataFile
destroy LogFile
destroy Handler

deactivate Handler
@enduml