@startuml
skinparam sequenceReferenceBackgroundColor lightblue


mainframe **sd** initialiseBot
participant "handler:Handler" as Handler
participant "logFile:LogFile" as LogFile
participant "dataFile:DataFile" as DataFile
participant "output:Output" as Output
participant "validation:Validation" as Validation

activate Handler #salmon

Handler -> Output: printWelcomeBanner()
activate Output #FFBBBB
Output --> Handler: 
deactivate Output


Handler -> LogFile: writeLog()
activate LogFile #FFBBBB
LogFile --> Handler:
deactivate LogFile

Handler -> DataFile: loadDataFile()
activate DataFile #FFBBBB
DataFile --> Handler: status
deactivate DataFile

alt data file present
    Handler -> DataFile: readDataFile()
    activate DataFile #FFBBBB
    DataFile --> Handler:
    
    alt no file read error
    
        deactivate DataFile #DarkSalmon
        Handler -> Output: printGreeting()
        activate Output #FFBBBB
        Output --> Handler
        deactivate Output #FFBBBB
        
    else file read error
        Handler -> Output: printException()
        activate Output #FFBBBB
        Output --> Handler
        deactivate Output #FFBBBB
    end

else datafile not present
    Handler -> Output: printGreeting()
    activate Output #FFBBBB
    Output --> Handler
    deactivate Output

    Handler -> Handler: userInduction()
    activate Handler #darksalmon
    ref over Handler: userInduction
    note right 
        The implementation of userInduction() has been omitted to keep the diagram
        simple.
    end note
end
@enduml