@startuml
mainframe **sd** validateWeightsArray
participant "handler:Handler" as Handler
participant "validation:Validation" as Validation

activate Handler #Salmon
Handler -> Validation: validateWeightsArray()
activate Validation #salmon

loop string in weightsArray
    
    alt weight is invalid number
        Validation --> Handler: InvalidInput exception
    end
    alt weight < 0
        Validation --> Handler: InvalidInput exception
    end

    alt weight > 2850
        Validation --> Handler: InvalidInput exception
    end

    alt weight % 0.125 != 0
        Validation --> Handler: InvalidInput exception
    end

    Validation -> Validation: validatedWeightsArray.add()
end

Validation --> Handler: validatedWeightsArray
deactivate Validation
@enduml