actor User
skinparam sequenceReferenceBackgroundColor lightblue
participant PulsePilot as PulsePilot << Class >>
participant Handler as Handler << Class >>
participant Output as Output << Class >>


User -> PulsePilot: start pulsepilot
activate PulsePilot #salmon
PulsePilot -> Handler: initialiseBot()
activate Handler #darksalmon
ref over Handler: initialiseBot()
Handler --> PulsePilot:
PulsePilot --> User: pulsepilot ready


loop user does not exit
    User -> PulsePilot: user input
    PulsePilot -> Handler: processInput()

    alt no error
    Handler --> User: processed command


    else error in input
    Handler -> Output: printException()
    activate Output #FFBBBB
    Output --> User: error message
    deactivate Output
    end
end

User -> PulsePilot: exit command
PulsePilot -> Handler: terminateBot()
ref over Handler: terminateBot()
Handler --> PulsePilot: 
PulsePilot --> User: exit pulsepilot
deactivate Handler
deactivate PulsePilot
deactivate User